config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root 'articles#index'
  resources :messages, only: [:index, :show, :create] do
    collection do
    	get 'inbox'
			get 'outbox'
    end
	end


  resources :articles do
  	resources :messages, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/Ken.rb
class Ken

	def self.ken_get 
		kens = [
		    '北海道', '青森県', '岩手県', '宮城県', '秋田県', 
		    '山形県', '福島県', '茨城県', '栃木県', '群馬県', 
		    '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', 
		    '富山県', '石川県', '福井県', '山梨県', '長野県', 
		    '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', 
		    '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県', 
		    '鳥取県', '島根県', '岡山県', '広島県', '山口県', 
		    '徳島県', '香川県', '愛媛県', '高知県', '福岡県', 
		    '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', 
		    '鹿児島県', '沖縄県'
				]

		kens.each.with_index(1) do |k,i|
		  Prefecture.create(id: i, ken:k)
		end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :messages


  validates :title,  presence: true
	#validates :date,   presence: true
	validates :place,  presence: true
	validates :genre,  presence: true
  validates :norma,  presence: true
	validates :detail, presence: true
  validates :area,   presence: true

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
               styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
               content_type: ["image/jpg","image/jpeg","image/png"]


  has_many :articles
  has_many :messages

  validates :name,  presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters,  if: :devise_controller?

  def after_sign_out_path_for(resource)
    '/users/sign_in'
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :avatar)
    devise_parameter_sanitizer.for(:account_update).push(:name, :avatar)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:search,:show]
  def index
    @articles = Article.order('updated_at DESC').limit(5)
  end

  def search
    @prefs = Prefecture.all
		@articles = Article.where('area LIKE(?)', "%#{params[:area]}%").order('updated_at DESC').page(params[:page]).per(10)
    @articles = @articles.where('genre LIKE(?)', "%#{params[:genre]}%").order('updated_at DESC').page(params[:page]).per(10)
		@articles = @articles.where('date LIKE(?)', "%#{params[:date]}%").order('updated_at DESC').page(params[:page]).per(10)
    @articles = @articles.where('detail LIKE(?)', "%#{params[:detail]}%").order('updated_at DESC').page(params[:page]).per(10)
  end

  def show
    @article = Article.find(params[:id])
    @message = Message.new
  end

  def new
    @prefs = Prefecture.all
    @article = Article.new  
  end

  def create 
    @article = Article.new(article_params)
    if @article.save
       @article.save
    else
			@prefs = Prefecture.all
    	render :new
    end
  end

  def edit
    @prefs = Prefecture.all
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    
		article.title  = article_params[:title]
		article.area   = article_params[:area]
		article.place  = article_params[:place]
		article.genre  = article_params[:genre]
		article.norma  = article_params[:norma]
		article.detail = article_params[:detail]

    if article.save
      article.update(article_params)
    else
      @prefs = Prefecture.all
    	@article = article
      render :new
    end
  end

  def destroy
    article = Article.find(params[:id])
    if article.user_id == current_user.id
      article.destroy
    end
  end

  private
  def article_params
    params.require(:article).permit(:title,:date,:area,:place,:genre,:norma,:detail).merge(user_id: current_user.id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index

	end

	def inbox
    @reception_messages = Message.where(recever_id: current_user.id).order('updated_at DESC').page(params[:page]).per(5)
	end

	def outbox
	  @send_messages = current_user.messages.order('updated_at DESC').page(params[:page]).per(5)
	end


  def show
    @message = Message.find(params[:id])
	end

	def create
    Message.create(title: message_params[:title], text: message_params[:text], article_id: message_params[:article_id], recever_id: message_params[:recever_id], user_id: current_user.id)
  end

  private
  def message_params
    params.permit(:title, :text, :article_id, :recever_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @articles = user.articles.order('updated_at DESC').page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/create.html.erb
<div id="confirmBox"> 
  <p>投稿完了</p>
  <a href="/">戻る</a>
</div>

app/views/articles/destroy.html.erb
  <p>削除しました</p>

  <a href="/">戻る</a>

app/views/articles/edit.html.erb
<div id="newBox">
	<h2>記事の編集</h2>

	<% if @article.errors.any? %>
	  <div id="errorBox">
	    <h3><%= @article.errors.count %>件のエラーがあります。</h3>
	 
	    <ul>
	    <% @article.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

  <dl>
	  <%= form_for @article do |f| %>
	  	<dt><%= f.label :タイトル %></dt>
	    <dd><%= f.text_field :title %></dd>
	   
	    <dt><%= f.label :日付 %></dt>
	    <dd><%= f.date_select :date, :use_month_unmbers => true %></dd>

	    <dt><%= f.label :エリア %></dt>
	    <dd><%= f.select :area , @prefs.map{|pref| [pref.ken]} %></dd>
	  
	    <dt><%= f.label :場所 %></dt>
	    <dd><%= f.text_field :place %></dd>

	    <dt><%= f.label :ジャンル %></dt>
	    <dd><%= f.text_field :genre %></dd>
	    
	    <dt><%= f.label :ノルマ %></dt>
	    <dd><%= f.text_field :norma %></dd>

	    <dt><%= f.label :詳細 %></dt>
	    <dd><%= f.text_area :detail, size: "70x10" %></dd>
	    
	    <%= button_tag type:"submit" do %>
	      投稿する
	    <% end %>
	  <% end %>
	</dl>
</div>

app/views/articles/index.html.erb
<div id="mainImgBox">
	<div id="mainMessageBox">
		<strong>素敵な出会いをあなたに</strong>
		<span>さぁ、ライブをはじめよう。</span>
	</div>
</div>

<div id="outlineBox">
	<h2>マイページ</h2>
	<dl>
  <% if user_signed_in? %>
    <%= image_tag current_user.avatar, :size => "200x250", :align => "center" %>
   	<dt><%= current_user.name %>さん</dt>
		<dd><%= link_to "メッセージリスト",  messages_path %></dd>
		<dd><a href="/users/<%= current_user.id %>">記事の管理</a></dd>
		<dd><%= link_to "プロフィールの管理", edit_user_registration_path %></dd>
		<dd><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></dd>
	<% else %>
	  <dd><%= link_to "ログイン",  new_user_session_path %></dd>
		<dd><%= link_to "新規登録",  new_user_registration_path %></dd>
	<% end %>
	</dl>
</div>

<div id="conceptBox">
	<h2>当サイトについて</h2>
  <span>バンドをはじめたばかりの方にとって、出演できるライブイベントを探すのは大変なこと。<br>
        また、イベンターの方にとっても出演者を集める為のPRに苦労していることでしょう。<br>
	     	当サイトでは、そんな方々のお役に立てるような、ライブにブッキングを手助けしています。</span>
</div>

<div id="topicsBox">
	<h2>新着記事</h2>
	<dl class="clearfix">
	<% @articles.each do |article| %>
		<dt><%= article.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></dt>
		<dd><a href="/articles/<%= article.id %>"><%= article.title %></a></dd>
	<% end %>
	</dl>
</div>

app/views/articles/new.html.erb
<div id="newBox">
  <h2>記事の新規投稿</h2>

	<% if @article.errors.any? %>
	  <div id="errorBox">
	    <h3><%= @article.errors.count %>件のエラーがあります。</h3>
	 
	    <ul>
	    <% @article.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>



  <dl>
	  <%= form_for @article  do |f| %>
	    <dt><%= f.label :タイトル %></dt>
	    <dd><%= f.text_field :title %></dd>

	    <dt><%= f.label :日付 %></dt>
	    <dd><%= f.date_select :date, :use_month_unmbers => true %></dd>

	    <dt><%= f.label :エリア %></dt>
	    <dd><%= f.select :area , @prefs.map{|pref| [pref.ken]} %></dd>

	    <dt><%= f.label :場所 %></dt>
	    <dd><%= f.text_field :place, placeholder: "ライブハウス名等を記入" %></dd>

	    <dt><%= f.label :ジャンル %></dt>
	    <dd><%= f.text_field :genre %></dd>

	    <dt><%= f.label :ノルマ %></dt>
	    <dd><%= f.text_field :norma %></dd>

	    <dt><%= f.label :詳細 %></dt>
	    <dd><%= f.text_area :detail, size: "70x20" %></dd>

	    <%= button_tag type:"submit" do %>
	      投稿する
	    <% end %>

	  <% end %>
  </dl>
</div>

app/views/articles/search.html.erb
<div id="searchBox">
	<h2>ライブを検索する</h2>
  <%= form_tag('/articles/search/', method: :get) do %>

    <dt>日程：</dt>
		<dd><input type="date" name="date"></dd>

		<dt>エリア：</dt>
    <dd><select name="area">
          <option value="">選択して下さい</option>
        <% @prefs.each do |pref| %>
					<option value="<%= pref.ken %>"><%= pref.ken%></option>
        <% end %>
    </select></dd>

		<dt>ジャンル：</dt>
    <dd><input type="text" name="genre"></dd>

    <dt>キーワード：</dt>
		<dd><input type="text" name="detail"></dd>

    <dt><input type="submit" value="検索"></dt>
  <% end %>
</div>
<div id="topicsBox">
	<h2>検索結果</h2>
	<dl>
	<% @articles.each do |article| %>
		<dt><%= article.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></dt>
		<dd><a href="/articles/<%= article.id %>"><%= article.title %></a></dd>
	<% end %>
	</dl>

  <div class="clearfix">
 		<%= paginate(@articles) %>
  </div>
</div>

app/views/articles/show.html.erb
<div id="showBox">
	<h2>記事の詳細</h2>
	<dl>
	  <dt>記事タイトル ： </dt>
    <dd><%=@article.title %></dd>
	  <dt>投稿者 ： </dt>
    <dd><%=@article.user.name %></dd>
	  <dt>日付 ： </dt>
    <dd><%= @article.date %></dd>
	  <dt>エリア ： </dt>
    <dd><%= @article.area %></dd>
	  <dt>場所 ： </dt>
    <dd><%= @article.place %></dd>
	  <dt>ジャンル ： </dt>
    <dd><%= @article.genre %></dd>
	  <dt>ノルマ ： </dt>
    <dd><%= @article.norma %></dd>
	  <dt>詳細 ： <dt>
    <dd><%= @article.detail %></dd>
	</dl>
</div>

<div id="sendMessageBox">
	<% if current_user && current_user.id != @article.user_id %>
	  <h2>このイベントについてメッセージを送る</h2>
    <dl>
	  <%= form_tag("/articles/#{@article.id}/messages", method: :post) do %>
	     <dt>タイトル<input type="text" name="title" size="50" value="『<%=@article.title %>』についての問い合わせ"></dt>
	     <dt>本文<textarea cols="50" name="text" placeholder="メッセージの記入" cols="70" rows="20"></textarea></dt>
           <input type="hidden" name="recever_id" value="<%= @article.user_id %>">
	     <dt><input type="submit" value="メッセージを送る"></dt>
	  <% end %>
    </dl>
	<% end %>
</div>

app/views/articles/update.html.erb
  <p>編集完了</p>

  <a href="/">戻る</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiveBooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">

		<div id="bgHeader">
			<div id="header" class="clearfix">
				<h1><%= link_to 'LIVE BOOKING', root_path, method: :get %></h1>
				<ul id="gNavi" class="clearfix">
					<li class="firstItem"><%= link_to '投稿する', new_article_path, method: :get %></li>
					<li class="lastItem"><%= link_to 'ライブを探す', search_articles_path, method: :get %></li>
				</ul>
			</div>
		</div>

    <div id="bgColor">

		  <div id="mainContents" class="clearfix">
			 	<%= yield %>
	    </div>

			<div id="footer">
				<p id="copyright">Copyright hashimoto All Rights Reserved.</p>
			</div>

    </div>
	</div>
</body>
</html>

app/views/messages/create.html.erb
  <p>メッセージを送信しました</p>

  <a href="/">戻る</a>

app/views/messages/inbox.html.erb
<div id="messageBox">

  <h2>メッセージリスト</h2>
	<h5><%=link_to "受信ボックス", inbox_messages_path %></h5>
  <h5><%=link_to "送信ボックス", outbox_messages_path %></h5>


 	<h2>受信ボックス</h2>
	<dl class="clearfix">
	<% @reception_messages.each do |res| %>
		<dt><%= res.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></dt>
		<dd><a href="/messages/<%= res.id %>"><%= res.title %></a><span id="send">送信者：<%= res.user.name%></span></dd>
	<% end %>
	</dl>
	<div class="clearfix">
  	<%= paginate(@reception_messages) %>
  </div>
</div>

app/views/messages/index.html.erb
<div id="messageBox">

  <h2>メッセージリスト</h2>
	<h5><%=link_to "受信ボックス", inbox_messages_path %></h5>
  <h5><%=link_to "送信ボックス", outbox_messages_path %></h5>

</div>

app/views/messages/outbox.html.erb
<div id="messageBox">

  <h2>メッセージリスト</h2>
	<h5><%=link_to "受信ボックス", inbox_messages_path %></h5>
  <h5><%=link_to "送信ボックス", outbox_messages_path %></h5>


  <h2>送信ボックス</h2>
	<dl class="clearfix">
	<% @send_messages.each do |send| %>
		<dt><%= send.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></dt>
		<dd><a href="/messages/<%= send.id %>"><%= send.title %></a></dd>
	<% end %>
	</dl>

  <div class="clearfix">
  	<%= paginate(@send_messages) %>
  </div>
</div>

app/views/messages/show.html.erb
<div id="showBox">
	<h2>メッセージ詳細</h2>
  <dl>
		<dt>タイトル</dt>
    	<dd><%= @message.title%></dd>
		<dt>送信者</dt>
    	<dd><%= @message.user.name %></dd>
		<dt>本文</dt>
      <dd><%= @message.text%></dd>
  </dl>
</div>

<div id="sendMessageBox">
	<% if current_user.id ==  @message.recever_id %>
  	<h2>このメッセージに返信をする</h2>
    <dl>
  	<%= form_tag("/messages", method: :post) do %>
    	<dt>タイトル<input type="text" name="title" size="50" value="RE:<%=@message.title %>"></dt>
     	<dt>本文<textarea name="text" cols="70" rows="20"></textarea></dt>
		 	<input type="hidden" name="article_id" value="<%= @message.article.id %>">
      <input type="hidden" name="recever_id" value="<%= @message.user_id %>">
     	<dt><input type="submit" value="返信する"></dt>
   	<% end %>
		</dl>
	<% end %>
</div>

app/views/users/show.html.erb
<div id="usersArticleBox">
	<h2>投稿した記事の管理</h2>
	<dl>
		<% @articles.each do |article| %>
		<dt><a href="/articles/<%= article.id %>"><%= article.title %></a></dt>
		<dd>
		  <%= link_to "編集", "/articles/#{article.id}/edit"  , method: :get %>
		  <%= link_to "削除", "/articles/#{article.id}" , method: :delete %>
		</dd>
		<% end %>
	</dl>

  <div class="clearfix">
 		<%= paginate(@articles) %>
  </div>
</div>